name: Integration tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  test-integration:
    name: integration tests on ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
            ref: feature/rebranding

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout plugin
        uses: actions/checkout@v4

      - name: Checkout app
        uses: actions/checkout@v4
        with:
          repository: dex4er/freelens
          ref: ${{ matrix.ref }}
          path: freelens

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Get npm cache directory
        shell: bash
        run: echo "npm_cache_dir=$(npm config get cache)" >> ${GITHUB_ENV}

      - name: Use cache
        uses: actions/cache@v4
        with:
          path: ${{ env.npm_cache_dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Move app to upper directory
        shell: bash
        run: mv freelens ..

      - name: Install dependencies for app
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 20
          max_attempts: 3
          retry_on: error
          command: cd ../freelens && npm ci

      - name: Install dependencies for plugin
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_on: error
          command: yq -oj -pj '.devDependencies["@freelensapp/extensions"]="../freelens/packages/extension-api"' package.json && npm ci

      - name: Build app
        run: cd ../freelens && npm run build

      - name: Build plugin
        run: npm run build

      - name: Pack plugin
        run: npm pack

      - name: Get extension path
        shell: bash
        run: echo "EXTENSION_PATH=$(find $(pwd) -name '*.tgz')" >> ${GITHUB_ENV}

      - name: Copy tests from plugin to app
        run: rm -f ../freelens/freelens/integration/__tests__/* && cp integration/__tests__/* ../freelens/freelens/integration/__tests__

      - name: Install minikube
        uses: medyagh/setup-minikube@master
        with:
          kubernetes-version: v1.30.1

      - name: Build Electron app
        run: cd ../freelens && npm run build:app -- -- -- dir --${{ matrix.arch }}

      - name: Run integration tests
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 15
          max_attempts: 3
          retry_on: timeout
          command: cd ../freelens && npm run test:integration
