name: Automated tag

on:
  issue_comment:
    types:
      - created

permissions:
  contents: write
  id-token: write
  pull-requests: read

jobs:
  create-tag:
    if: >
      startsWith(github.event.issue.title, 'Automated npm version') &&
      github.event.issue.state == 'closed' &&
      github.event.comment.body == '/tag'

    runs-on: ubuntu-24.04
    environment: automated

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Get version from package.json
        id: package-json
        run: |
          echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Create tag from the main branch
        if: steps.package-json.outputs.version
        uses: actions/github-script@v7
        with:
          script: |
            const mainRef = await github.rest.git.getRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'heads/main',
            });
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.package-json.outputs.version }}',
              sha: mainRef.data.object.sha,
            })
